name: CI
on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.0'
    - name: Setup Dependencies
      run:  |
        go version
        go get -u golang.org/x/lint/golint
        go get -u github.com/gorilla/mux    
    - name: Run Build
      run: go build .
    - name: Run Linter
      run: |
        go vet .
        golint .
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
   # - name: Step to add manual approval
    #  uses: trstringer/manual-approval@v1
     # with:
      #  secret: ${{ github.TOKEN }}
       # approvers: heloise-viegas
       # minimum-approvals: 1
       # issue-title: "Check code before deployment"      
    - name: Step to build docker image
      run: docker build . --file Dockerfile --tag go-image-crud-api


      
      
      
  
